/**
 *  Point of contact for container modules
 *
 *  e.g.: import { Home, About } from 'containers'
 *
 */

export Admin from './Admin/Admin'
export AdminDestinationList from './AdminDestinationList/AdminDestinationList'
export AdminDestinationListItem from './AdminDestinationListItem/AdminDestinationListItem'
export AdminDestinationListItemEdit from './AdminDestinationListItemEdit/AdminDestinationListItemEdit'
export AdminTrippianList from './AdminTrippianList/AdminTrippianList'
export AdminTrippianListItem from './AdminTrippianListItem/AdminTrippianListItem'
export AdminTrippianListItemEdit from './AdminTrippianListItemEdit/AdminTrippianListItemEdit'
export AdminInquiryList from './AdminInquiryList/AdminInquiryList'
export AdminInquiryListItem from './AdminInquiryListItem/AdminInquiryListItem'
export AdminInquiryListItemEdit from './AdminInquiryListItemEdit/AdminInquiryListItemEdit'
export AdminTripList from './AdminTripList/AdminTripList'
export AdminTripListItem from './AdminTripListItem/AdminTripListItem'
export AdminTripListItemEdit from './AdminTripListItemEdit/AdminTripListItemEdit'
export AdminUserList from './AdminUserList/AdminUserList'
export AdminUserListItem from './AdminUserListItem/AdminUserListItem'
export AdminUserListItemEdit from './AdminUserListItemEdit/AdminUserListItemEdit'

export About from './About/About'
export App from './App/App'
  // export Calendar from './Calendar/Calendar'
export Chat from './Chat/Chat'
export Contact from './Contact/Contact'
export Destination from './Destination/Destination'
export DestinationDetail from './DestinationDetail/DestinationDetail'
export DestinationList from './DestinationList/DestinationList'
export DestinationPost from './DestinationPost/DestinationPost'
export DestinationSearchResults from './DestinationSearchResults/DestinationSearchResults'
export PopularDestinations from './PopularDestinations/PopularDestinations'
export DestinationWrapper from './DestinationWrapper/DestinationWrapper'
export EmailNotification from './EmailNotification/EmailNotification'
export InquiryAdd from './InquiryAdd/InquiryAdd'
export InquiryList from './InquiryList/InquiryList'
export InquiryDetail from './InquiryDetail/InquiryDetail'
export IntlDemo from './IntlDemo/IntlDemo'
export Home from './Home/Home'
export JoinUs from './JoinUs/JoinUs'
export Login from './Login/Login'
export LoginSuccess from './LoginSuccess/LoginSuccess'
export Logout from './Logout/Logout'
export LoginWrapper from './LoginWrapper/LoginWrapper'
export Press from './Press/Press'
  // export LoginSuccess from './LoginSuccess/LoginSuccess'
export NotFound from './NotFound/NotFound'
  // export Review from './Review/Review'
export Signup from './Signup/Signup'
export SignupSuccess from './SignupSuccess/SignupSuccess'
export SignupWrapper from './SignupWrapper/SignupWrapper'
export TeamCards from './About/TeamCards'
export Terms from './Terms/Terms'
export Trippian from './Trippian/Trippian'
export TrippianDetail from './TrippianDetail/TrippianDetail'
export TrippianSignUp from './TrippianSignUp/TrippianSignUp'
export TrippianList from './TrippianList/TrippianList'
export TrippianEdit from './TrippianEdit/TrippianEdit'

export Dashboard from './Dashboard/Dashboard'
export MyProfile from './Dashboard/MyProfile'
export MyInquiries from './Dashboard/MyInquiries'
export MyPostedTrips from './Dashboard/MyPostedTrips'
export MyTripBox from './Dashboard/MyTripBox'

export Trips from './Trips/Trips'
