/**
 *  Point of contact for container modules
 *
 *  e.g.: import { Home, About } from 'containers'
 *
 */

export Admin from './Admin/Admin'
export AdminInquiryList from './AdminInquiryList/AdminInquiryList'
export AdminTrippianList from './AdminTrippianList/AdminTrippianList'
export AdminDestinationList from './AdminDestinationList/AdminDestinationList'
export AdminDestinationListItem from './AdminDestinationListItem/AdminDestinationListItem'
export AdminDestinationListItemEdit from './AdminDestinationListItemEdit/AdminDestinationListItemEdit'
export AdminTrippianList from './AdminTrippianList/AdminTrippianList'
export AdminTrippianListItem from './AdminTrippianListItem/AdminTrippianListItem'
export AdminTrippianListItemEdit from './AdminTrippianListItemEdit/AdminTrippianListItemEdit'
export About from './About/About'
export App from './App/App'
  // export Calendar from './Calendar/Calendar'
export Chat from './Chat/Chat'
export DestinationDetail from './DestinationDetail/DestinationDetail'
export DestinationList from './DestinationList/DestinationList'
export DestinationPost from './DestinationPost/DestinationPost'
export EmailNotification from './EmailNotification/EmailNotification'
export InquiryAdd from './InquiryAdd/InquiryAdd'
export InquiryList from './InquiryList/InquiryList'
export InquiryDetail from './InquiryDetail/InquiryDetail'
export IntlDemo from './IntlDemo/IntlDemo'
export Home from './Home/Home'
export JoinUs from './JoinUs/JoinUs'
export Login from './Login/Login'
export Press from './Press/Press'
  // export LoginSuccess from './LoginSuccess/LoginSuccess'
export NotFound from './NotFound/NotFound'
  // export Review from './Review/Review'
export TeamCards from './About/TeamCards'
export Terms from './Terms/Terms'
export TrippianDetail from './TrippianDetail/TrippianDetail'
export TrippianSignUp from './TrippianSignUp/TrippianSignUp'
export TrippianList from './TrippianList/TrippianList'
export TrippianEdit from './TrippianEdit/TrippianEdit'
  // export Trips from './Trips/Trips'
